### PR TITLE
Fix typo in docker-run example

### PR DESCRIPTION
**Pull request by shioyama**

### CODE REVIEW

**Comment by displague** [comment]
Thanks for the report, @shioyama!

This actually appears to be documented correctly.  `--rm` refers to a single option, while `-it` is an argument list that covers two options.

```
$ docker run --rm -it debian bash
Unable to find image 'debian:latest' locally
latest: Pulling from library/debian
54f7e8ac135a: Pull complete
Digest: sha256:df6ebd5e9c87d0d7381360209f3a05c62981b5c2a3ec94228da4082ba07c4f05
Status: Downloaded newer image for debian:latest
root@69983ba0d600:/#
```

I realize that `it` looks confusing because it reads as a word!

**Comment by shioyama** [comment]
Hmm, are you sure? This is what I get with `--it` (which this PR changes to `-it`):

```
λ ~/ docker run --rm -it debian bash                                                                         
root@6404c87cd5b8:/# exit
λ ~/ docker run --rm --it debian bash                                                                        
unknown flag: --it
See 'docker run --help'.
```

Version:

```
λ ~/ docker -v                                                                                               
Docker version 18.09.0-ce, build 4d60db472b
```

**Comment by displague** [comment]
Oh! You are absolutely correct.  My apologies.

**Comment by shioyama** [comment]
Thanks!

**Pull request merged**
